### ISSUE TITLE
LoR of VEF 2.0

### ISSUE THREAD

**Issue by anhtienng** [nguyenthanhvuh/phd-cs-us#10]
Can you explain more about why the VEF LoRs are effective ?
How can a Professor who have not supervised a candidate provide a "strong" LoR ?

Thank you.

**Comment by nguyenthanhvuh** [comment]
They write the LoR based on a 1-hr interview that is quite intensive, asking the applicant about their existing research and various technical skills, goals, motivations, etc.  So not as a good as someone who has supervised the student for a years, but it is still good.  

Another thing is VEF LoRs are typically from US faculty, who know how to write good LoRs. In contrast, LoR writers in Vietnam might not be very well-known researcher internationally.  In many cases they do not know how to write LoRs, or they ask students to write their own.  Such letters are likely weak and so the VEF letters can help.
