### ISSUE TITLE
Department having only 1 Professor who matches my research interests

### ISSUE THREAD

**Issue by anhtienng** [nguyenthanhvuh/phd-cs-us#11]
Hello Vu,

I have a list of department with Professors who have the same research topic with me.
However, there are some departments that only have one Professor only.

Should I apply for those departments ? 

Thank you.

**Comment by nguyenthanhvuh** [comment]
it's up to you. If you feel you have good connection with them, then apply.

**Comment by anhtienng** [comment]
Thank you
