### ISSUE TITLE
PhD in other related fields

### ISSUE THREAD

**Issue by anhtienng** [nguyenthanhvuh/phd-cs-us#12]
Hello Vu, 

In your document, you mentioned about doing `PhD in other related fields`, but still working on CS topics.

Can you add more comparison of doing PhD in CS and other related fields (like ECE, Biomedical Engineering,...) ? 
Such as:
- The courses in other departments could not relevant to CS, there are very few courses in ECE that are relevant to CS.
- The admission process in CS is more competitive than other departments (my opinion).
- Is the CS PhD could be more valuable when looking for CS jobs ?

Thank you.

**Comment by nguyenthanhvuh** [comment]
I don't know other fields well so I can't compare them with CS.  The main point of that section in the document is that you don't need to do CS PhD to do CS research.

**Comment by anhtienng** [comment]
Thank you.
